### ISSUE TITLE
Left navigation tree

### ISSUE THREAD

**Issue by hzzou** [nickcam/d3-StackedTimeline#2]
hello,I want to add the left navigation tree.Click to expand or collapse on the left side, followed by linkage on the right side.I have been researching the current project for some time.But the progress is not very big.Could you help me?

**Comment by nickcam** [comment]
Hi, I think I understand what you mean. Haven't looked at this project in a while to be honest, and won't have time to get into the guts of it to update it. I think this could be fairly tricky, have you considered looking at other projects?

**Comment by hzzou** [comment]
to be honest,I have been looking for on github a long time.Only your project is best for my needs. And I have applied it to my project. I think you should be familiar with your project, it should be much easier to modify.

**Comment by nickcam** [comment]
I just don't have the time to commit to making large changes at the moment sorry. 
Anyway, can you send some screenshots of what you're thinking and even what you've tried so far?

I was thinking of a tree view type control on the left hand side that could be expanded and collapsed. This would also cause the timeline rows to expand and collapse.

If I get a chance I'll take a look, but can't guarantee anything sorry.
